@startuml

[Фронт]
[Админка]

[Сервис операций]
[Сервис шаблонов операций]

[Сервис чеков]
[Сервис полнотекстового поиска]
[Сервис карт]
[Сервис ленты операций]

[Сервис заказа]
[Антифрод]
[Сервис процессинга операций]
[Сервис безопасности]
[Процессинг]

database "Mongo1" {
   [Operation template]
}

database "Mongo2" {
   [Operation]
}

database "PostgresQL1" {
   [Full-text]
}

database "PostgresQL2" {
   [Check]
}

database "PostgresQL3" {
   [Order]
}

database "PostgresQL4" {
   [Account]
}

database "PostgresQL5" {
   [Security]
}

database "PostgresQL6" {
   [Processing]
}

database "PostgresQL7" {
    [Camunda]
}

database "Kafka1" {
   [T.Full-text]
}

database "Kafka2" {
   [T.Result]
}

database "Kafka3" {
   [T.Run-process]
}

database "Kafka4" {
   [T.Step-process]
}

database "Kafka5" {
   [T.AFR-in]
}

database "Kafka6" {
   [T.AFR-out]
}

database "Elastic" {
   [E.Full-text]
}


[Фронт] --> [Сервис шаблонов операций]
[Фронт] --> [Сервис операций]
[Фронт] --> [Сервис карт]
[Фронт] --> [Сервис чеков]
[Фронт] --> [Сервис полнотекстового поиска]
[Фронт] --> [Сервис ленты операций]

[Админка] --> [Сервис шаблонов операций]
[Админка] --> [Сервис процессинга операций]
[Админка] --> [Антифрод]

[Сервис шаблонов операций] --> [T.Full-text]
[Сервис шаблонов операций] --> [Operation template]

[Сервис операций] --> [Operation]
[Сервис операций] --> [T.Full-text]
[Сервис операций] --> [Сервис заказа]
[Сервис операций] --> [Сервис карт]

[T.Full-text] --> [Сервис полнотекстового поиска]

[Сервис полнотекстового поиска] --> [E.Full-text]
[Сервис полнотекстового поиска] --> [Full-text]

[Сервис чеков] --> [Сервис операций]
[Сервис чеков] --> [Check]

[Сервис ленты операций] --> [Operation] : RO
[Сервис ленты операций] --> [Order] : RO

[Сервис карт] --> [Account]

[Сервис заказа] --> [Сервис безопасности]
[Сервис заказа] --> [Процессинг]
[Сервис заказа] --> [T.Result]
[Сервис заказа] --> [T.Run-process]
[Сервис заказа] --> [Order]

[T.Result] --> [Сервис операций]

[T.Run-process] --> [Сервис процессинга операций]

[T.Step-process] --> [Сервис заказа]

[Сервис безопасности] --> [Security]
[Сервис безопасности] --> [ОПСОС]

[Процессинг] --> [Processing]
[Процессинг] --> [Visa/Mastercard]

[T.AFR-in] --> [Антифрод]

[Антифрод] --> [T.AFR-out]

[T.AFR-out] --> [Сервис процессинга операций]

[Сервис процессинга операций] --> [Процессинг]
[Сервис процессинга операций] --> [T.AFR-in]
[Сервис процессинга операций] --> [T.Step-process]
[Сервис процессинга операций] --> [Camunda]

@enduml